### ISSUE TITLE
Outdated dependencies in package.json

### ISSUE THREAD

**Issue by mliebischer** [rohberg/volto-accordion-block#1]
**Describe the bug**

This addon seems to be broken due to some dependencies on the deprecated addon `@eeacms/volto-blocks-form` in `package.json`.

Error:
```
12Edit.jsx:218 Uncaught TypeError: _plone_volto_registry__WEBPACK_IMPORTED_MODULE_13__.default.settings.richTextEditorPlugins is not iterable
```

**To Reproduce**

1. Add addon to your `package.json` of your Volto installation 

  ```json
"addons": [
    "@rohberg/volto-accordion-block"
],

"dependencies": {
    "@rohberg/volto-accordion-block": "^0.1.0"
}
  ```
3. Start Volto with `yarn start`
4. Click on the button to add/edit the content
9. **ERROR**

**Software:**

Tested with Volto 15.12.1 and Plone 6.0.0a4.

**Additional information**

Since this package is no longer needed anyway, it can simply be removed from the `package.json` to fix the problem (see this commit https://github.com/rohberg/volto-accordion-block/commit/ec0536ff13ed85adb90f092b8329e699fd62eb5b#diff-c986a9cd783848dd4ad769e1c52106d0e024a019daa2c4a3cb0d1875551bf8e0L8)

**Comment by ksuess** [comment]
You may want to have a look at https://github.com/eea/volto-accordion-block. It is far more elaborated, as the accordion items can contain blocks. 
I should mark this repo as superseeded and archived. Sorry for the inconvenience.

**Comment by mliebischer** [comment]
Hi Katja, there is nothing to apologize for. :-) This is a nice little addon and a good starting point to inspect and explore.

As this addon is currently used and referenced in `FAQ block type` example in "[Mastering Plone 6 Development](https://training.plone.org/5/mastering-plone/volto_custom_addon2.html#)" I thought it would be a good idea to at least keep it working. 

I also submitted a PR with the same fixes to make the code example work within the training as well.
https://github.com/plone/training/pull/626
